version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: super-cursos
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h db -U user']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    image: super-cursos-backend
    ports:
      - '5000:5000'
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    image: super-cursos-frontend
    ports:
      - '3000:3000'
